### ISSUE TITLE
Guest Checkout

### ISSUE THREAD

**Issue by nicksarr1** [siteoptimo/woocommerce-hear-about-us#2]
Where will this info be saved if a guest doesn't create an account and checks out. Can it be saved to the order itself? 

Also, If I can be added to the order. Can it be added to a column in the orders section of woocommerce? 
Thank you for helping with the questions and for created this plugin!
- Nick

**Comment by nicksarr1** [comment]
Awesome thanks for taking it as a consideration!

**Comment by pieterc** [comment]
Hi nick, the feature to add the visitor source location to the order has now been added to release 1.1.0. We'll push it to the WordPress plugin directory today.
