### ISSUE TITLE
Ask the source only once.

### ISSUE THREAD

**Issue by pieterc** [siteoptimo/woocommerce-hear-about-us#4]
Once a customer has left it's source at checkout, it shouldn't be asking it the next time, or at least give the admin the choice to disable this field after the first checkout.
https://wordpress.org/support/topic/any-update-on-when-the-new-customers-only-addition?replies=2

**Comment by greguly** [comment]
Are you doing this already?

If not, I can make a PR which will store the informed 'source' at user meta and a check to not asking twice.

**Comment by vdwijngaert** [comment]
Hey @greguly, we didn't start developing this yet, so if you would like to do it, you are more than welcome to! Just send us a pull request and we'll integrate it. Thanks!

**Comment by greguly** [comment]
Ok, we have a deal.  :-) 

It will take me 2 days...

**Comment by vdwijngaert** [comment]
Hey @greguly,

Are you still working on this? If not, no hard feelings and I'll integrate it.

**Comment by greguly** [comment]
Hiya.

Allow me just a couple of hours more and I'll PR :-)

**Comment by vdwijngaert** [comment]
Great, thanks :)

**Comment by greguly** [comment]
There is a small issue with using the plugin without first saving the settings, I am fixing it

**Comment by greguly** [comment]
Hmm, I can't reproduce it now....

**Comment by greguly** [comment]
https://github.com/siteoptimo/woocommerce-hear-about-us/pull/5 :-)

**Comment by vdwijngaert** [comment]
Thanks, @greguly !

**Comment by greguly** [comment]
:+1:
